on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:

  prepare:
    name: Prepare - ${{ inputs.environment }}
    #needs: project
    environment: ${{ inputs.environment }}
    runs-on: [otc-static]
    outputs:
       aws_cloud_enabled: ${{ steps.get_project.outputs.aws_cloud_enabled }}
       azr_cloud_enabled: ${{ steps.get_project.outputs.azr_cloud_enabled }}
       gcp_cloud_enabled: ${{ steps.get_project.outputs.gcp_cloud_enabled }}
       aws_regions: ${{ steps.get_project.outputs.aws_regions }}
       azr_regions: ${{ steps.get_project.outputs.azr_regions }}
       gcp_regions: ${{ steps.get_project.outputs.gcp_regions }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Project
        id: get_project
        run: |
         FILE="${{ github.workspace }}/.otc/project.tfvars.json"
         echo "otc_backend=`jq -c '.otc.otc_backend' $FILE`" >> "$GITHUB_OUTPUT"
         echo "otc_region=`jq -c '.otc.otc_region' $FILE`" >> "$GITHUB_OUTPUT"
         echo "aws_cloud_enabled=`jq -c '.project.aws_cloud_enabled' $FILE`" >> "$GITHUB_OUTPUT"
         echo "azr_cloud_enabled=`jq -c '.project.azr_cloud_enabled' $FILE`" >> "$GITHUB_OUTPUT"
         echo "gcp_cloud_enabled=`jq -c '.project.gcp_cloud_enabled' $FILE`" >> "$GITHUB_OUTPUT"
         echo "aws_regions=`jq -c '.project.aws_regions' $FILE`" >> "$GITHUB_OUTPUT"
         echo "azr_regions=`jq -c '.project.azr_regions' $FILE`" >> "$GITHUB_OUTPUT"
         echo "gcp_regions=`jq -c '.project.gcp_regions' $FILE`" >> "$GITHUB_OUTPUT"
         echo "File: $FILE"
      - name: Configure AWS Credentials
        if: ${{ fromJson(steps.get_project.outputs.otc_backend)=='aws' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN}}
          aws-region: ${{ fromJson(steps.get_project.outputs.otc_region) }}
      - name: 'Authenticate to GCP'
        if: ${{ fromJson(steps.get_project.outputs.otc_backend)=='gcp' }}
        uses: 'google-github-actions/auth@v0.3.1'
        with:
            create_credentials_file: 'true'
            workload_identity_provider: ${{ secrets.GCP_PROVIDER_NAME}}
            service_account: ${{ secrets.GCP_SA_EMAIL}}
      - name: Deploy Backend
        uses: otc-code/gh-actions/terraform@main
        with:
          TERRAFORM_ACTION: 'create_backend'
          TF_DIR: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_PARTIAL_BACKEND_FILE: '${{ github.workspace }}/.otc/${{ inputs.environment }}.tfbackend'
          CLOUD_REGION: ${{ fromJson(steps.get_project.outputs.otc_region) }}
