on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      token:
        required: false
jobs:

  packer_build:
    runs-on: [otc-static]
    name: Build AMI
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: |
            if ! command -v packer &> /dev/null; then
              echo "packer could not be found, installing."
              sudo apt-get update &> /dev/null && sudo apt-get install -y gnupg software-properties-common curl  &> /dev/null
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -  &> /dev/null
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" &> /dev/null
              sudo apt-get update && sudo apt-get -y install packer &> /dev/null
            fi
            echo "Packer: `which packer` - `packer --version`"
        shell: bash

      - name: Configure AWS Credentials
        if: ${{ fromJson(steps.get_backend.outputs.otc_backend)=='aws' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN}}
          aws-region: 'eu-central-1'

      - name: Packer Init & Validate
        working-directory: ./packer/
        run: |
            packer init .
            packer validate .
        shell: bash

      - name: Packer Build AMI
        working-directory: ./packer/
        run: |
            packer build .
        shell: bash
