on:
  workflow_call:
    inputs:
      deployment:
        required: false
        type: string
        default: 'false'
    secrets:
      token:
        required: false

jobs:
  tf_docs:
    name: Update docs
    runs-on: [otc-static]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ORG_TOKEN }}
      - name: Update - Docs
        uses: otc-code/gh-actions/docs@main
        with:
          TF_DIR: '${{ github.workspace }}'
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
      - name: Update TF branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git checkout -b "auto/otc-changes"
          git push --force origin "auto/otc-changes"
